### ISSUE TITLE
autofixup fails when run from a subdirectory

### ISSUE THREAD

**Issue by campbellr** [torbiak/git-autofixup#1]
This morning I accidentally tried to run `git autofixup` from a subdirectory of my git repo instead of the root. It failed with the following error:

```
[~/git/q44586-prodscript/q45459] (master) $ git autofixup @{u}
fatal: cannot stat path 'q45459/HEAD': No such file or directory
git blame: non-zero exit code at /localhome/campbr9/perl5/bin/git-autofixup line 324.

```

It's a pretty small thing, but it would be nice if I didn't have to care where i was in the git repo when I run the command.

**Comment by torbiak** [comment]
Thanks. I'm almost always at the root of my projects, so I consistently forget about this.

**Comment by campbellr** [comment]
Thanks!
