### ISSUE TITLE
"corrupt patch" error re-adding a newline at the end of a file

### ISSUE THREAD

**Issue by torbiak** [torbiak/git-autofixup#2]
@campbellr was adding back a newline at the end of a file that had been removed in a previous commit and received a "corrupt patch" error.

I'm guessing the patch is being represented as a list containing a single empty string, and joining that with newlines produces...an empty string, which is an invalid patch for git.

**Comment by torbiak** [comment]
My guess was way wrong: I was actually parsing hunks incorrectly and stopped collecting lines for a hunk when a "\ No newline at end of file" message was encountered.

**Comment by campbellr** [comment]
Thanks @torbiak!
