### ISSUE TITLE
FYI: alternative implementations

### ISSUE THREAD

**Issue by aspiers** [torbiak/git-autofixup#7]
This is not an issue, so feel free to close straight away, but I thought you might be interested to know about my alternative implementation:

- https://github.com/aspiers/git-deps/blob/master/bin/git-fixup
- https://github.com/aspiers/git-deps/blob/master/USE-CASES.md#use-case-4-automatic-squashing-of-fixup-commits

There are others too:

- https://github.com/tummychow/git-absorb - written in Rust, doesn't use `blame`, only searches 10 most recent commits by default
- https://github.com/bertoldia/git-absorb - written in Go, doesn't (yet?) automatically figure out the right ancestor

**Comment by torbiak** [comment]
Nice, thanks. git-deps looks really cool. And I know Axel, but wasn't aware he'd worked on that Go implementation.
